local _, L = ...;
if GetLocale() == "deDE" then
	L.L["Last Scan"] = "Letzter Scan"
	L.L["Rank"] = "Rang"
	L.L["Mog War"] = "Mog-Krieg"
	L.L["Archive"] = "Archiv"
	L.L["Winner"] = "Sieger"
	L.L["Shared by %s: %s"] = "Geteilt von %s: %s"
	L.L["Scanned %s-%s: %s"] = "Gescannt %s-%s: %s"
	L.L["Show an alert in chat on a successful mog scan."] = "Eine Benachrichtigung im Chat bei einem erfolgreichen Mog-Scan anzeigen."
	L.L["Scan Alerts"] = "Scan-Benachrichtigungen"
	L.L["%d (%dW - %dL - %dC)%s"] = "%d (%dS - %dN - %dV)%s"
	L.L["Class"] = "Klasse"
	L.L["wins"] = "siege"
	L.L["w"] = "s"
	L.L["losses"] = "niederlagen"
	L.L["l"] = "n"
	L.L["rating"] = "wertung"
	L.L["rank"] = "rang"
	L.L["r"] = "r"
	L.L["Item scan is complete after %s."] = "Der Gegenstandsscan ist nach %s abgeschlossen."
	L.L["There was an error (%s)"] = "Es ist ein Fehler aufgetreten (%s)"
	L.L["Starting Item scan."] = "Gegenstandsscan wird gestartet."
end
