local _, L = ...;
if GetLocale() == "ptBR" then
	L.L["Last Scan"] = "Última verificação"
	L.L["Rank"] = "Classificação"
	L.L["Mog War"] = "Guerra Mog"
	L.L["Archive"] = "Arquivo"
	L.L["Winner"] = "Vencedor"
	L.L["Shared by %s: %s"] = "Compartilhado por %s: %s"
	L.L["Scanned %s-%s: %s"] = "Escaneado %s-%s: %s"
	L.L["Show an alert in chat on a successful mog scan."] = "Mostrar um alerta no chat quando uma varredura de Mog for bem-sucedida."
	L.L["Scan Alerts"] = "Alertas de varredura"
	L.L["%d (%dW - %dL - %dC)%s"] = "%d (%dV - %dD - %dC)%s"
	L.L["Class"] = "Classe"
	L.L["wins"] = "vitórias"
	L.L["w"] = "v"
	L.L["losses"] = "derrotas"
	L.L["l"] = "d"
	L.L["rating"] = "classificação"
	L.L["rank"] = "patente"
	L.L["r"] = "p"
	L.L["Item scan is complete after %s."] = "A verificação de itens foi concluída após %s."
	L.L["There was an error (%s)"] = "Ocorreu um erro (%s)"
	L.L["Starting Item scan."] = "Iniciando a verificação de itens."
end
